version: '3'

services:
  mongodb-cron-backup:
    image: randyproxz/mongodb-cron-backup
    container_name: mongo-cron-backup
    volumes:
      - ./data/backup:/backup
    environment:
      TZ: 'Asia/Jakarta' # set Timezone
      MONGO_HOST: 'host.docker.internal'
      MONGO_PORT: 27017
      MONGO_USER: 'admindb' # set empty if no user specified
      MONGO_DB: 'mydb' # set empty if you want backup all db
      MONGO_PASS: '123qwe' # set empty if no password specified
      CRON_TIME: '* * * * *'
      INIT_BACKUP: 1
      MAX_BACKUPS: 3
